# GitHub Actions Workflow definition to automatically create a new release for each new Git tag

name: release

on:
  issues: 
    types: 
      [created, edited]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Unshallow
        run: git fetch --prune --unshallow
      - id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF##*/}

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.16'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.7.0
        with:
          version: v0.171.0
          args: release 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
